import { escapeHtml } from '@roos/security';
import { ANALYTICS_JS, APP_JS, LANDING_JS, PAYMENTS_JS, SERVER_JS, STORE_JS, STYLES_CSS, VALIDATE_JS } from './blueprint/runtime';
import { GENERATOR_VERSION, type EntitySpec, type MvpSpec } from './spec';

export interface GeneratedFile {
  path: string;
  content: string;
}

const SQL_TYPES: Record<string, string> = { string: 'text', text: 'text', number: 'double precision', boolean: 'boolean', date: 'date', email: 'text', url: 'text' };
const OAS_TYPES: Record<string, Record<string, string>> = {
  string: { type: 'string', maxLength: '200' },
  text: { type: 'string', maxLength: '5000' },
  number: { type: 'number' },
  boolean: { type: 'boolean' },
  date: { type: 'string', format: 'date' },
  email: { type: 'string', format: 'email' },
  url: { type: 'string', format: 'uri' },
};
export const SAMPLE_VALUES: Record<string, unknown> = { string: 'Sample value', text: 'Some longer notes', number: 42, boolean: true, date: '2026-01-15', email: 'test@example.com', url: 'https://example.com/page' };

const snake = (s: string) => s.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase();
const ident = (s: string) => `"${snake(s).replace(/"/g, '')}"`;

function specModule(spec: MvpSpec): string {
  const runtime = { name: spec.name, tagline: spec.tagline, entities: spec.entities, pricingTiers: spec.pricingTiers, variants: spec.variants, headlines: spec.headlines };
  return `// Generated by ${GENERATOR_VERSION}. Runtime configuration for this MVP.\nexport const SPEC = ${JSON.stringify(runtime, null, 2)};\n`;
}

function landingHtml(spec: MvpSpec): string {
  const e = escapeHtml;
  const features = spec.coreFeatures.map((f) => `        <div class="card"><p>${e(f)}</p></div>`).join('\n');
  const tiers = spec.pricingTiers
    .map(
      (t) => `        <div class="card">
          <h3>${e(t.name)}</h3>
          <p class="price">$${e(t.priceUsdMonthly)}<span class="muted">/mo</span></p>
          <ul>${t.features.map((f) => `<li>${e(f)}</li>`).join('')}</ul>
          <button type="button" data-tier="${e(t.name)}">Choose ${e(t.name)}</button>
        </div>`,
    )
    .join('\n');
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${e(spec.name)} — ${e(spec.tagline)}</title>
  <meta name="description" content="${e(spec.valueProposition)}">
  <link rel="stylesheet" href="/static/styles.css">
</head>
<body>
  <main>
    <header class="hero">
      <span class="badge">Early access</span>
      <h1 id="headline">${e(spec.headlines[spec.variants[0]!] ?? spec.tagline)}</h1>
      <p class="lead">${e(spec.valueProposition)}</p>
      <form id="signup-form" class="signup">
        <input name="name" placeholder="Your name" autocomplete="name" maxlength="100">
        <input name="email" type="email" placeholder="you@company.com" autocomplete="email" required maxlength="254">
        <button type="submit">Get early access</button>
      </form>
      <p id="signup-message" role="status"></p>
    </header>
    <section>
      <h2>The problem</h2>
      <p class="muted">${e(spec.problem)}</p>
      <p class="muted">Built for: ${e(spec.targetCustomer)}</p>
    </section>
    <section>
      <h2>What you get</h2>
      <div class="grid">
${features}
      </div>
    </section>
    <section>
      <h2>Planned pricing</h2>
      <p class="muted">Prices are provisional while we validate the product. You will not be charged without explicit confirmation.</p>
      <div class="grid">
${tiers}
      </div>
      <p id="pricing-message" class="muted" role="status"></p>
    </section>
    <footer>
      <p>${e(spec.name)} is an early-access product. We only use your email to contact you about ${e(spec.name)}; reply "unsubscribe" at any time.</p>
      <p><a href="/app">Open the app</a></p>
    </footer>
  </main>
  <script id="roos-config" type="application/json">__ROOS_CONFIG__</script>
  <script src="/static/landing.js"></script>
</body>
</html>
`;
}

function appHtml(spec: MvpSpec): string {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(spec.name)}</title>
  <link rel="stylesheet" href="/static/styles.css">
</head>
<body>
  <main>
    <h1>${escapeHtml(spec.name)}</h1>
    <p class="muted">${escapeHtml(spec.tagline)}</p>
    <div id="app"></div>
  </main>
  <script src="/static/app.js"></script>
</body>
</html>
`;
}

function schemaSql(spec: MvpSpec): string {
  const tables = spec.entities.map((en) => {
    const cols = en.fields.map((f) => {
      const check = f.type === 'email' ? ` CHECK (position('@' in ${ident(f.name)}) > 1)` : f.type === 'url' ? ` CHECK (${ident(f.name)} ~ '^https?://')` : '';
      return `  ${ident(f.name)} ${SQL_TYPES[f.type]}${f.required ? ' NOT NULL' : ''}${check}`;
    });
    return `CREATE TABLE ${ident(en.plural.replace(/-/g, '_'))} (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n${cols.join(',\n')},\n  created_at timestamptz NOT NULL DEFAULT now(),\n  updated_at timestamptz NOT NULL DEFAULT now()\n);`;
  });
  return `-- ${spec.name}: PostgreSQL schema (generated by ${GENERATOR_VERSION}).
-- The MVP ships with a JSON-file store; apply this schema when moving to PostgreSQL.

CREATE TABLE signups (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE CHECK (position('@' in email) > 1),
  name text,
  ref text,
  variant text,
  anonymous_id text,
  created_at timestamptz NOT NULL DEFAULT now()
);

${tables.join('\n\n')}
`;
}

function openApi(spec: MvpSpec): string {
  const schemas: Record<string, unknown> = {};
  const paths: Record<string, unknown> = {
    '/health': { get: { summary: 'Health check', responses: { '200': { description: 'OK' } } } },
    '/api/signup': {
      post: {
        summary: 'Join the early-access list',
        requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['email'], properties: { email: { type: 'string', format: 'email' }, name: { type: 'string' }, ref: { type: 'string' }, anonymousId: { type: 'string' }, variant: { type: 'string' } } } } } },
        responses: { '201': { description: 'Signed up' }, '400': { description: 'Invalid email' } },
      },
    },
    '/api/events': { post: { summary: 'Record a client funnel event', responses: { '202': { description: 'Accepted' } } } },
    '/api/checkout': { post: { summary: 'Start checkout (501 until a payment link is approved)', responses: { '200': { description: 'Payment URL' }, '501': { description: 'Payments not enabled' } } } },
  };
  for (const en of spec.entities) {
    schemas[en.name] = {
      type: 'object',
      required: en.fields.filter((f) => f.required).map((f) => f.name),
      properties: Object.fromEntries(en.fields.map((f) => [f.name, OAS_TYPES[f.type]])),
    };
    const ref = { $ref: `#/components/schemas/${en.name}` };
    paths[`/api/${en.plural}`] = {
      get: { summary: `List ${en.plural}`, responses: { '200': { description: 'OK' } } },
      post: { summary: `Create ${en.name}`, requestBody: { required: true, content: { 'application/json': { schema: ref } } }, responses: { '201': { description: 'Created' }, '400': { description: 'Validation failed' } } },
    };
    paths[`/api/${en.plural}/{id}`] = {
      parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
      get: { summary: `Get ${en.name}`, responses: { '200': { description: 'OK' }, '404': { description: 'Not found' } } },
      put: { summary: `Update ${en.name}`, requestBody: { content: { 'application/json': { schema: ref } } }, responses: { '200': { description: 'Updated' } } },
      delete: { summary: `Delete ${en.name}`, responses: { '204': { description: 'Deleted' } } },
    };
  }
  return JSON.stringify({ openapi: '3.1.0', info: { title: spec.name, version: '0.1.0', description: spec.valueProposition }, paths, components: { schemas } }, null, 2) + '\n';
}

function testFile(): string {
  // Generic test-suite driven by lib/spec.js — exercises every generated entity.
  return String.raw`import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { createServer } from '../server.js';
import { SPEC } from '../lib/spec.js';

const SAMPLES = { string: 'Sample value', text: 'Some longer notes', number: 42, boolean: true, date: '2026-01-15', email: 'test@example.com', url: 'https://example.com/page' };
let server;
let base;

before(async () => {
  const dir = mkdtempSync(path.join(process.env.DATA_DIR || os.tmpdir(), 'mvp-test-'));
  server = createServer({ dataDir: dir });
  await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve));
  base = 'http://127.0.0.1:' + server.address().port;
});

after(() => new Promise((resolve) => server.close(resolve)));

const json = (method, p, body) => fetch(base + p, { method, headers: { 'content-type': 'application/json' }, body: body === undefined ? undefined : JSON.stringify(body) });

test('health endpoint responds', async () => {
  const r = await fetch(base + '/health');
  assert.equal(r.status, 200);
  assert.equal((await r.json()).ok, true);
});

test('landing page is served with security headers and injected config', async () => {
  const r = await fetch(base + '/');
  assert.equal(r.status, 200);
  assert.match(r.headers.get('content-security-policy'), /default-src 'self'/);
  assert.equal(r.headers.get('x-frame-options'), 'DENY');
  const html = await r.text();
  assert.ok(!html.includes('__ROOS_CONFIG__'), 'config placeholder must be replaced');
  const cfg = JSON.parse(html.split('<script id="roos-config" type="application/json">')[1].split('</script>')[0]);
  assert.deepEqual(cfg.variants, SPEC.variants);
});

test('signup validates email addresses', async () => {
  assert.equal((await json('POST', '/api/signup', { email: 'not-an-email' })).status, 400);
  assert.equal((await json('POST', '/api/signup', { email: '<script>@x' })).status, 400);
  assert.equal((await json('POST', '/api/signup', { email: 'person@example.com', name: 'Pat' })).status, 201);
  const again = await json('POST', '/api/signup', { email: 'person@example.com' });
  assert.equal((await again.json()).duplicate, true);
});

test('rejects malformed and oversized bodies', async () => {
  const bad = await fetch(base + '/api/signup', { method: 'POST', headers: { 'content-type': 'application/json' }, body: '{nope' });
  assert.equal(bad.status, 400);
  const big = await json('POST', '/api/signup', { email: 'a@b.co', name: 'x'.repeat(70000) });
  assert.equal(big.status, 413);
});

test('blocks path traversal on static files', async () => {
  assert.equal((await fetch(base + '/static/..%2Fserver.js')).status, 404);
  assert.equal((await fetch(base + '/static/../../server.js')).status, 404);
});

test('checkout is disabled until a payment link is approved', async () => {
  const r = await json('POST', '/api/checkout', { tier: SPEC.pricingTiers[0] && SPEC.pricingTiers[0].name });
  assert.equal(r.status, 501);
});

for (const entity of SPEC.entities) {
  test('CRUD for ' + entity.name, async () => {
    const payload = {};
    for (const f of entity.fields) payload[f.name] = SAMPLES[f.type];
    const created = await json('POST', '/api/' + entity.plural, payload);
    assert.equal(created.status, 201);
    const item = await created.json();
    assert.ok(item.id);
    const list = await (await fetch(base + '/api/' + entity.plural)).json();
    assert.ok(list.items.some((x) => x.id === item.id));
    const first = entity.fields[0];
    const upd = await json('PUT', '/api/' + entity.plural + '/' + item.id, { [first.name]: SAMPLES[first.type] });
    assert.equal(upd.status, 200);
    assert.equal((await json('DELETE', '/api/' + entity.plural + '/' + item.id)).status, 204);
    assert.equal((await fetch(base + '/api/' + entity.plural + '/' + item.id)).status, 404);
  });

  test('validation for ' + entity.name, async () => {
    const required = entity.fields.filter((f) => f.required);
    const r = await json('POST', '/api/' + entity.plural, {});
    assert.equal(r.status, required.length ? 400 : 201);
    const typed = entity.fields.find((f) => f.type === 'number' || f.type === 'email' || f.type === 'date');
    if (typed) {
      const payload = {};
      for (const f of entity.fields) payload[f.name] = SAMPLES[f.type];
      payload[typed.name] = 'definitely-invalid';
      assert.equal((await json('POST', '/api/' + entity.plural, payload)).status, 400);
    }
  });
}
`;
}

function dockerfile(): string {
  return `# Generated by ${GENERATOR_VERSION}
FROM node:24-alpine
WORKDIR /app
COPY --chown=node:node . .
RUN mkdir -p /data && chown node:node /data
USER node
ENV NODE_ENV=production HOST=0.0.0.0 PORT=3000 DATA_DIR=/data
EXPOSE 3000
HEALTHCHECK --interval=30s --timeout=3s CMD wget -qO- http://127.0.0.1:3000/health || exit 1
CMD ["node", "server.js"]
`;
}

function readme(spec: MvpSpec, files: string[]): string {
  return `# ${spec.name}

> ${spec.tagline}

Generated by **${GENERATOR_VERSION}** for opportunity \`${spec.provenance.opportunityId ?? 'n/a'}\` / hypothesis \`${spec.provenance.hypothesisId ?? 'n/a'}\` (${spec.provenance.businessModel ?? 'n/a'}) on ${spec.provenance.generatedAt}.

## Run

\`\`\`bash
node server.js            # http://127.0.0.1:3000  (landing page) and /app (product)
node --test --test-isolation=none test/server.test.js
\`\`\`

No dependencies — nothing to install.

## Environment

| Variable | Purpose |
|---|---|
| \`PORT\` / \`HOST\` | Listen address (default 127.0.0.1:3000) |
| \`DATA_DIR\` | Where the JSON store lives (default ./data) |
| \`ROOS_TRACK_URL\` / \`ROOS_WRITE_KEY\` | Forward funnel events to ROOS (experiment measurement) |
| \`ROOS_EXPERIMENT_ID\` | Attach events to a running ROOS experiment |
| \`ROOS_VARIANTS_JSON\` | Override landing-page variants: \`{"variants":["a","b"],"headlines":{"a":"…"}}\` |
| \`PAYMENT_LINK_URL\` | Stripe payment link — created in ROOS **only after human approval** |

## Deploy

\`Dockerfile\` and \`docker-compose.yml\` are included; see \`deploy/README.md\`. Production deployment is an
approval-gated action in ROOS.

## Assumptions (review before publishing)

${spec.provenance.assumptions.map((a) => `- ${a}`).join('\n')}

## Files

${files.map((f) => `- \`${f}\``).join('\n')}
`;
}

function specMd(spec: MvpSpec): string {
  return `# Product specification — ${spec.name}

**Tagline:** ${spec.tagline}

**Problem:** ${spec.problem}

**Target customer:** ${spec.targetCustomer}

**Value proposition:** ${spec.valueProposition}

## Core features
${spec.coreFeatures.map((f) => `- ${f}`).join('\n')}

## Data model
${spec.entities.map((e: EntitySpec) => `### ${e.name} (\`/api/${e.plural}\`)\n${e.fields.map((f) => `- \`${f.name}\`: ${f.type}${f.required ? ' (required)' : ''}`).join('\n')}`).join('\n\n')}

## Pricing (${spec.pricingKind})
${spec.pricingTiers.map((t) => `- **${t.name}** — $${t.priceUsdMonthly}/month: ${t.features.join(', ')}`).join('\n')}

## Onboarding
${spec.onboardingSteps.map((s, i) => `${i + 1}. ${s}`).join('\n')}

## Analytics events
${spec.analyticsEvents.map((a) => `- \`${a.event}\` — ${a.when}`).join('\n')}

## Success metrics
${spec.successMetrics.map((m) => `- ${m.metric}: ${m.target}`).join('\n') || '- Defined by the linked ROOS experiment'}

## Experiment variants
${spec.variants.map((v) => `- \`${v}\`: ${spec.headlines[v] ?? spec.tagline}`).join('\n')}
`;
}

/** Produce every file of the MVP. Pure function — writing is done by `writeProject`. */
export function generateProject(spec: MvpSpec): GeneratedFile[] {
  const files: GeneratedFile[] = [
    {
      path: 'package.json',
      content:
        JSON.stringify(
          {
            name: spec.slug || 'mvp',
            version: '0.1.0',
            private: true,
            type: 'module',
            description: spec.tagline,
            engines: { node: '>=20' },
            scripts: { start: 'node server.js', test: 'node --test --test-isolation=none test/server.test.js' },
          },
          null,
          2,
        ) + '\n',
    },
    { path: 'server.js', content: SERVER_JS },
    { path: 'lib/spec.js', content: specModule(spec) },
    { path: 'lib/store.js', content: STORE_JS },
    { path: 'lib/validate.js', content: VALIDATE_JS },
    { path: 'lib/analytics.js', content: ANALYTICS_JS },
    { path: 'lib/payments.js', content: PAYMENTS_JS },
    { path: 'public/index.html', content: landingHtml(spec) },
    { path: 'public/app.html', content: appHtml(spec) },
    { path: 'public/landing.js', content: LANDING_JS },
    { path: 'public/app.js', content: APP_JS },
    { path: 'public/styles.css', content: STYLES_CSS },
    { path: 'schema.sql', content: schemaSql(spec) },
    { path: 'openapi.json', content: openApi(spec) },
    { path: 'test/server.test.js', content: testFile() },
    { path: 'Dockerfile', content: dockerfile() },
    { path: '.dockerignore', content: 'data\nnode_modules\n.env\n' },
    {
      path: 'docker-compose.yml',
      content: `services:\n  app:\n    build: .\n    ports:\n      - "127.0.0.1:3000:3000"\n    environment:\n      ROOS_TRACK_URL: \${ROOS_TRACK_URL:-}\n      ROOS_WRITE_KEY: \${ROOS_WRITE_KEY:-}\n      ROOS_EXPERIMENT_ID: \${ROOS_EXPERIMENT_ID:-}\n      PAYMENT_LINK_URL: \${PAYMENT_LINK_URL:-}\n    volumes:\n      - data:/data\n    read_only: true\n    tmpfs: [/tmp]\n    security_opt: [no-new-privileges:true]\n    cap_drop: [ALL]\nvolumes:\n  data: {}\n`,
    },
    {
      path: 'deploy/fly.toml',
      content: `# Example Fly.io config — deploying to production requires approval in ROOS.\napp = "${spec.slug || 'mvp'}"\n\n[build]\n  dockerfile = "../Dockerfile"\n\n[env]\n  PORT = "3000"\n  DATA_DIR = "/data"\n\n[[mounts]]\n  source = "data"\n  destination = "/data"\n\n[http_service]\n  internal_port = 3000\n  force_https = true\n\n  [[http_service.checks]]\n    grace_period = "10s"\n    interval = "30s"\n    method = "GET"\n    path = "/health"\n    timeout = "3s"\n`,
    },
    {
      path: 'deploy/README.md',
      content: `# Deploying ${spec.name}\n\n1. Approve the \`deploy.production\` request in the ROOS approval center.\n2. Build: \`docker build -t ${spec.slug || 'mvp'} .\`\n3. Run anywhere that runs containers, e.g. \`fly launch --config deploy/fly.toml\` or \`docker compose up -d\`.\n4. Set \`ROOS_TRACK_URL\`, \`ROOS_WRITE_KEY\` and \`ROOS_EXPERIMENT_ID\` so funnel events reach ROOS.\n5. Only set \`PAYMENT_LINK_URL\` after the \`billing.configure\` approval created the payment link.\n`,
    },
    { path: '.env.example', content: 'PORT=3000\nHOST=127.0.0.1\nDATA_DIR=./data\nROOS_TRACK_URL=http://localhost:4000/api/track\nROOS_WRITE_KEY=\nROOS_EXPERIMENT_ID=\nROOS_VARIANTS_JSON=\nPAYMENT_LINK_URL=\n' },
    { path: 'SPEC.md', content: specMd(spec) },
    { path: 'roos.json', content: JSON.stringify({ generator: GENERATOR_VERSION, provenance: spec.provenance, spec }, null, 2) + '\n' },
  ];
  files.push({ path: 'README.md', content: readme(spec, files.map((f) => f.path).concat('README.md')) });
  return files;
}
